#!/bin/sh
# Regenerates the share image and icons from the SVG sources in this folder.
# Requires rsvg-convert + ImageMagick (brew install librsvg imagemagick) and the
# fonts referenced in the SVGs (Georgia / Inter / Menlo). Sources were generated by
# an MDO3D SEO-sweep script; edit the SVGs directly to change copy or colors.
set -e
cd "$(dirname "$0")"
OUT=..
for f in *og-image.svg; do rsvg-convert -w 1200 -h 630 "$f" -o "$OUT/${f%.svg}.png"; done
if [ -f mark.svg ]; then
  cp mark.svg "$OUT/favicon.svg"
  rsvg-convert -w 180 -h 180 -b '#6366f1' mark.svg -o "$OUT/apple-touch-icon.png"
  rsvg-convert -w 192 -h 192 -b '#6366f1' mark.svg -o "$OUT/icon-192.png"
  rsvg-convert -w 512 -h 512 -b '#6366f1' mark.svg -o "$OUT/icon-512.png"
  T=$(mktemp -d); for s in 16 32 48; do rsvg-convert -w $s -h $s mark.svg -o "$T/$s.png"; done
  magick "$T/16.png" "$T/32.png" "$T/48.png" "$OUT/favicon.ico"; rm -rf "$T"
fi
